using Booklify.Domain.Commons;
using Booklify.Domain.Enums;

namespace Booklify.Domain.Entities;

/// <summary>
/// Lưu trữ kết quả AI processing cho chapter
/// </summary>
public class ChapterAIResult : BaseEntity
{
    /// <summary>
    /// Reference to the chapter
    /// </summary>
    public Guid ChapterId { get; set; }
    
    /// <summary>
    /// Navigation property to Chapter
    /// </summary>
    public virtual Chapter Chapter { get; set; } = null!;
    
    /// <summary>
    /// AI-generated summary in Vietnamese
    /// </summary>
    public string? Summary { get; set; }
    
    /// <summary>
    /// AI-generated Vietnamese translation
    /// </summary>
    public string? Translation { get; set; }
    
    /// <summary>
    /// Keywords extracted by AI (JSON array)
    /// </summary>
    public string? Keywords { get; set; }
    
    /// <summary>
    /// Flashcards generated by AI (JSON array)
    /// </summary>
    public string? Flashcards { get; set; }
    
    /// <summary>
    /// AI model used for processing
    /// </summary>
    public string? AIModel { get; set; }
    
    /// <summary>
    /// Which actions were processed (comma-separated)
    /// </summary>
    public string ProcessedActions { get; set; } = string.Empty;
    
    /// <summary>
    /// Processing status
    /// </summary>
    public EntityStatus Status { get; set; } = EntityStatus.Active;
} 